In [1]:
# ndarray
#NumPy’s array class is called  ndarray. It is also known by the alias array. 
# Note that numpy.array is not the same as the Standard Python Library class array.array, 
      #which only handles one-dimensional arrays and offers less functionality. 


In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
#a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT
print(a)

[1 2 3 4]


In [5]:
b = np.array([(1.5,2,3), (4,5,6)])
print(b)

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]


In [6]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)

[[ 1.+0.j  2.+0.j]
 [ 3.+0.j  4.+0.j]]


In [7]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [8]:
np.arange( 0, 2, 0.3 ) 

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [9]:
np.arange(12).reshape(4,3) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print(arr) 

[[1 2 3]
 [4 2 5]]


In [11]:
# An exemplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
 
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)

Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [12]:
# numpy.ndarray
# An array object represents a multidimensional, homogeneous array of fixed-size items
# A 3-dimensional array of size 3 x 3 x 3,

np.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],
       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],
       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
x = np.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],
       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],
       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

x.sum(0), x.sum(1), x.sum(2)

(array([[27, 30, 33],
        [36, 39, 42],
        [45, 48, 51]]), array([[ 9, 12, 15],
        [36, 39, 42],
        [63, 66, 69]]), array([[ 3, 12, 21],
        [30, 39, 48],
        [57, 66, 75]]))

In [15]:
# numpy.random.rand
#Random values in a given shape.

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1). 

np.random.rand(3,2)

# between 0 to 1


array([[ 0.4772182 ,  0.99624317],
       [ 0.37031674,  0.41851084],
       [ 0.47123772,  0.3630902 ]])

In [17]:
# numpy.random.randn
# Return a sample (or samples) from the “standard normal” distribution.

np.random.randn()


0.2739848209724747

In [18]:
# numpy.random.randint
np.random.randint(5, size=(2, 4))

array([[1, 1, 3, 0],
       [1, 0, 0, 3]])

In [19]:
np.random.randint(100, size=(2, 4))

array([[79, 82,  2, 29],
       [30, 20, 46, 83]])

In [20]:
np.random.randint(20,100, size=(2, 4))

array([[36, 24, 37, 37],
       [53, 62, 56, 32]])

In [26]:
# shuffle
arr = np.arange(9).reshape((3, 3))
print(arr)
np.random.shuffle(arr)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [0 1 2]
 [3 4 5]]


In [27]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([6, 0, 7, 8, 5, 1, 3, 9, 4, 2])